# Schema for the configuration files of the prepopulate_title module.
prepopulate_title.settings:
  type: config_object
  label: 'prepopulate_title settings'
  mapping:
    example:
      type: string
      label: 'Example'
